after_success:
  - npx codecov
  - npx codeclimate-test-reporter < ./coverage/lcov.info
cache:
  directories:
    - node_modules
language: node_js
node_js:
  - node
  - 8
notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/94a8a87b117fbc50ceaf'
    on_success: always
    on_failure: always
    on_start: never
os:
  - linux
