build: off
cache: node_modules
environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"
install:
  - ps: "Install-Product node $env:nodejs_version"
  - npm install
notifications:
  - on_build_failure: true
    on_build_status_changed: true
    on_build_success: true
    provider: Webhook
    url: "https://webhooks.gitter.im/e/f39a577444275f34d7e1"
test_script:
  - node --version
  - npm --version
  - npm test
version: "{build}"
